FROM nginx:latest
MAINTAINER Ozrlz

# Conf files
# COPY odoo-nginx.conf /etc/nginx/conf.d/
COPY odoo-nginx_ssl.conf /etc/nginx/conf.d/
COPY ./ssl /etc/nginx/ssl/

# Delete default files
RUN rm /etc/nginx/conf.d/default.conf 

# Expose 80 443 port, in which the users will interact with odoo services
EXPOSE 80 443
